project_id = "idomxajidxdpidecxktg"

[functions.send-order-email]
verify_jwt = false

[functions.stripe-checkout]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.create-cod-order]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false
