import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "ka" | "en" | "tr";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Georgian translations (primary)
const translations: Record<Language, Record<string, string>> = {
  ka: {
    // Site name
    "site.name": "ავტო ცენტრი",
    
    // Navigation
    "nav.home": "მთავარი",
    "nav.shop": "მაღაზია",
    "nav.catalysts": "კატალიზატორები",
    "nav.track_order": "შეკვეთის თვალყურისდევნება",
    "nav.brands": "ბრენდები",
    "nav.contact": "კონტაქტი",
    
    // Header
    "header.search_placeholder": "ნაწილების ძებნა...",
    
    // Hero
    "hero.badge": "უფასო მიწოდება 99₾-ზე მეტ შეკვეთებზე",
    "hero.title_1": "ყველაფერი თქვენი ავტომობილისთვის",
    "hero.title_2": "ერთ სივრცეში",
    "hero.browse_parts": "ნაწილების დათვალიერება",
    "hero.quality_guaranteed": "ხარისხი გარანტირებული",
    "hero.fast_delivery": "სწრაფი მიწოდება",
    
    // Categories
    "categories.title": "კატეგორიით შოპინგი",
    "categories.subtitle": "ავტომობილის ნაწილების კატალოგი კატეგორიების მიხედვით",
    
    // Category names
    "category.Brakes": "მუხრუჭები",
    "category.Suspension": "საკიდარი",
    "category.Engine": "ძრავი",
    "category.Lighting": "განათება",
    "category.Exhaust": "გამონაბოლქვი",
    "category.Transmission": "გადაცემათა კოლოფი",
    "category.Electrical": "ელექტრო",
    "category.Body Parts": "კარდანი",
    "category.Interior": "ინტერიერი",
    "category.Wheels & Tires": "საბურავები",
    
    // Category descriptions
    "category.desc.Brakes": "ბრეკის ბალიშები, დისკები, კალიპერები და დამაგრების ნაწილები უსაფრთხო დამუხრუჭებისთვის.",
    "category.desc.Electrical": "გენერატორები, სტარტერები, აკუმულატორები და ელექტრო გაყვანილობა.",
    "category.desc.Engine": "ფილტრები, სენსორები, ქამრები და ძრავის სატუნინგო დეტალები.",
    "category.desc.Exhaust": "მუფელები, მილები და გამონაბოლქვის ტუნინგ სისტემები.",
    "category.desc.Interior": "სავარძლები, მოპირკეთება, ბერკეტები და ინტერიერის აქსესუარები.",
    "category.desc.Lighting": "ფარები, სტოპ-სიგნალები, ნისლის ფარები და ლამპები.",
    "category.desc.Suspension": "საკიდარის ნაწილები, ამორტიზატორები და კომფორტის სისტემები.",
    "category.desc.Transmission": "გადაცემათა კოლოფის ნაწილები და აქსესუარები.",
    "category.desc.Body Parts": "კუზოვის ნაწილები, კარები, ფარები და აქსესუარები.",
    "category.desc.Wheels & Tires": "საბურავები, დისკები და საბურავების აქსესუარები.",
    
    // Featured Products
    "featured.title": "გამორჩეული პროდუქტები",
    "featured.subtitle": "ჩვენი საუკეთესო ავტონაწილები",
    "featured.add_to_cart": "კალათაში დამატება",
    "featured.view_details": "დეტალურად ნახვა",
    "featured.view_all": "ყველას ნახვა",
    
    // Brands
    "brands.title": "ტოპ ბრენდები",
    "brands.subtitle": "ჩვენ ვყიდით მსოფლიოს წამყვანი მწარმოებლების ნაწილებს",
    
    // Shop
    "shop.title": "ნაწილების მაღაზია",
    "shop.products_found": "ნაპოვნია პროდუქტი",
    "shop.search_products": "პროდუქტების ძებნა...",
    "shop.filters": "ფილტრები",
    "shop.no_products": "პროდუქტი ვერ მოიძებნა",
    "shop.clear_filters": "ფილტრების გასუფთავება",
    "shop.clear_all_filters": "ყველა ფილტრის გასუფთავება",
    
    // Filters
    "filter.find_by_vehicle": "მანქანით ძებნა",
    "filter.all_years": "ყველა წელი",
    "filter.all_makes": "ყველა მარკა",
    "filter.all_models": "ყველა მოდელი",
    "filter.category": "კატეგორია",
    "filter.all_categories": "ყველა კატეგორია",
    "filter.brand": "ბრენდი",
    "filter.all_brands": "ყველა ბრენდი",
    "filter.price_range": "ფასის დიაპაზონი",
    "filter.min": "მინ",
    "filter.max": "მაქს",
    
    // Product
    "product.add_to_cart": "კალათაში დამატება",
    "product.in_stock": "მარაგში",
    "product.out_of_stock": "ამოწურულია",
    "product.sku": "SKU",
    "product.oem_code": "OEM კოდი",
    "product.brand": "ბრენდი",
    "product.category": "კატეგორია",
    "product.compatibility": "თავსებადობა",
    "product.description": "აღწერა",
    "product.related": "მსგავსი პროდუქტები",
    "product.fits": "შეესაბამება",
    "product.present": "დღემდე",
    
    // Cart
    "cart.title": "კალათა",
    "cart.empty": "თქვენი კალათა ცარიელია",
    "cart.empty_desc": "როგორც ჩანს, ჯერ არ დაგიმატებიათ ნაწილები.",
    "cart.start_shopping": "შოპინგის დაწყება",
    "cart.subtotal": "ჯამი",
    "cart.shipping": "მიწოდება",
    "cart.free": "უფასო",
    "cart.free_shipping_note": "უფასო მიწოდება 99₾-ზე მეტ შეკვეთებზე",
    "cart.total": "სულ",
    "cart.proceed_checkout": "გადახდაზე გადასვლა",
    "cart.continue_shopping": "შოპინგის გაგრძელება",
    "cart.order_summary": "შეკვეთის შეჯამება",
    
    // Checkout
    "checkout.title": "გადახდა",
    "checkout.back_to_cart": "კალათაში დაბრუნება",
    "checkout.contact_info": "საკონტაქტო ინფორმაცია",
    "checkout.full_name": "სახელი და გვარი",
    "checkout.email": "ელ-ფოსტა",
    "checkout.phone": "ტელეფონი",
    "checkout.shipping_address": "მიწოდების მისამართი",
    "checkout.street_address": "მისამართი",
    "checkout.city": "ქალაქი",
    "checkout.postal_code": "საფოსტო კოდი",
    "checkout.country": "ქვეყანა",
    "checkout.additional_comment": "დამატებითი კომენტარი",
    "checkout.notes_placeholder": "განსაკუთრებული ინსტრუქციები თქვენი შეკვეთისთვის...",
    "checkout.payment": "გადახდის მეთოდი",
    "checkout.cod_title": "გადახდა ადგილზე",
    "checkout.cod_description": "თანხას გადაიხდით ადგილზე ნაღდად ან გადარიცხვით.",
    "checkout.place_order": "შეკვეთის გაფორმება",
    "checkout.name_required": "სახელი აუცილებელია",
    "checkout.phone_required": "ტელეფონი აუცილებელია",
    "checkout.country_required": "ქვეყანა აუცილებელია",
    "checkout.city_required": "ქალაქი აუცილებელია",
    "checkout.street_required": "მისამართი აუცილებელია",
    "checkout.postal_required": "საფოსტო კოდი აუცილებელია",
    "checkout.processing": "მუშავდება...",
    "checkout.phone_notice": "გადაზიდვის დეტალებზე დაგიკავშირდებათ ჩვენი მომხმარებელთა მომსახურება ტელეფონით.",
    
    // Checkout Success
    "success.title": "შეკვეთა წარმატებით გაფორმდა!",
    "success.thank_you": "მადლობა შეძენისთვის. თქვენი შეკვეთა დადასტურებულია და მუშავდება.",
    "success.order_id": "შეკვეთის ID",
    "success.cod_notice": "თანხას გადაიხდით ადგილზე ნაღდად ან გადარიცხვით კურიერთან/მიმღებთან.",
    "success.phone_notice": "გადაზიდვის დეტალებზე დაგიკავშირდებით ტელეფონით.",
    "success.continue_shopping": "შოპინგის გაგრძელება",
    "success.track_order": "შეკვეთის თვალყურისდევნება",
    "success.order_status_note": "თქვენ შეგიძლიათ ნებისმიერ დროს შეამოწმოთ შეკვეთის სტატუსი",
    
    // Checkout Cancel
    "cancel.title": "გადახდა გაუქმებულია",
    "cancel.message": "თქვენი გადახდა გაუქმდა. არ ინერვიულოთ - თქვენი კალათა შენახულია და შეგიძლიათ ხელახლა სცადოთ.",
    "cancel.retry": "ხელახლა ცდა",
    "cancel.return_to_cart": "კალათაში დაბრუნება",
    
    // Contact
    "contact.title": "დაგვიკავშირდით",
    "contact.subtitle": "გაქვთ კითხვები ნაწილების შესახებ ან გჭირდებათ დახმარება შეკვეთასთან დაკავშირებით? ჩვენ აქ ვართ დასახმარებლად.",
    "contact.phone": "ტელეფონი",
    "contact.email": "ელ-ფოსტა",
    "contact.reply_time": "ვპასუხობთ 24 საათში",
    "contact.address": "მისამართი",
    "contact.name": "სახელი",
    "contact.subject": "თემა",
    "contact.message": "შეტყობინება",
    "contact.send": "შეტყობინების გაგზავნა",
    "contact.sending": "იგზავნება...",
    "contact.sent": "შეტყობინება გაიგზავნა!",
    "contact.sent_desc": "მალე დაგიკავშირდებით.",
    "contact.error": "შეტყობინების გაგზავნა ვერ მოხერხდა. გთხოვთ სცადოთ თავიდან.",
    "contact.phone_optional": "ტელეფონი (არასავალდებულო)",
    
    // Order Lookup
    "order_lookup.title": "შეკვეთის ძებნა",
    "order_lookup.subtitle": "შეიყვანეთ შეკვეთის ID და ტელეფონის ნომერი სტატუსისა და თვალყურისდევნების ინფორმაციის სანახავად.",
    "order_lookup.find_order": "შეკვეთის მოძებნა",
    "order_lookup.order_id": "შეკვეთის ID",
    "order_lookup.phone": "ტელეფონის ნომერი",
    "order_lookup.hint": "გამოიყენეთ შეკვეთის ID (მაგ., #ABC12345) და თქვენი ტელეფონი",
    "order_lookup.search": "შეკვეთის მოძებნა",
    "order_lookup.searching": "ძებნა...",
    "order_lookup.not_found": "შეკვეთა ვერ მოიძებნა ამ ID-ითა და ტელეფონით.",
    "order_lookup.tracking": "თვალყურისდევნების ინფორმაცია",
    "order_lookup.tracking_number": "თვალყურისდევნების ნომერი",
    "order_lookup.carrier": "გადამზიდავი",
    "order_lookup.shipped_on": "გაიგზავნა",
    "order_lookup.track_shipment": "გზავნილის თვალყურისდევნება",
    "order_lookup.no_tracking": "თვალყურისდევნების დეტალები ჯერ მიუწვდომელია. თქვენ მიიღებთ ელ-წერილს როცა შეკვეთა გაიგზავნება.",
    "order_lookup.order_items": "შეკვეთის ნივთები",
    "order_lookup.payment": "გადახდა",
    "order_lookup.method": "მეთოდი",
    "order_lookup.status": "სტატუსი",
    "order_lookup.shipping_address": "მიწოდების მისამართი",
    
    // Order statuses
    "status.pending": "მოლოდინში",
    "status.confirmed": "დადასტურებული",
    "status.shipped": "გაგზავნილი",
    "status.completed": "დასრულებული",
    "status.canceled": "გაუქმებული",
    "status.paid": "გადახდილი",
    "status.failed": "წარუმატებელი",
    
    "status_message.pending": "თქვენი შეკვეთა ელოდება დადასტურებას.",
    "status_message.confirmed": "თქვენი შეკვეთა დადასტურებულია და მზადდება.",
    "status_message.shipped": "თქვენი შეკვეთა გზაშია!",
    "status_message.completed": "თქვენი შეკვეთა მიტანილია.",
    "status_message.canceled": "ეს შეკვეთა გაუქმებულია.",
    
    // Footer
    "footer.description": "თქვენი სანდო წყარო ხარისხიანი ავტონაწილებისთვის. გთავაზობთ ფართო არჩევანს ყველა ძირითადი ავტომობილის ბრენდისთვის.",
    "footer.contact": "კონტაქტი",
    "footer.rights_reserved": "ყველა უფლება დაცულია.",
    "footer.admin": "ადმინი",
    "footer.track_order": "შეკვეთის თვალყურისდევნება",
    "footer.social": "სოციალური ქსელები",
    "footer.available_24_7": "ვპასუხობთ 24/7",
    "footer.hours_weekday": "ორშ-შაბ 9:00-19:00",
    "footer.hours_sunday": "კვირა 9:00-17:00",
    
    // 404
    "notfound.title": "404",
    "notfound.message": "უპს! გვერდი ვერ მოიძებნა",
    "notfound.return": "მთავარზე დაბრუნება",
    
    // Common
    "common.loading": "იტვირთება...",
    "common.error": "შეცდომა",
    "common.save": "შენახვა",
    "common.cancel": "გაუქმება",
    "common.delete": "წაშლა",
    "common.edit": "რედაქტირება",
    "common.add": "დამატება",
    "common.qty": "რაოდ",
    "common.yes": "დიახ",
    "common.no": "არა",
    "common.confirm": "დადასტურება",
    "common.actions": "მოქმედებები",
    "common.name": "სახელი",
    "common.description": "აღწერა",
    "common.create": "შექმნა",
    "common.update": "განახლება",
    
    // Toasts
    "toast.added_to_cart": "დაემატა კალათაში",
    "toast.removed_from_cart": "ამოიშალა კალათიდან",
    "toast.cart_updated": "კალათა განახლდა",
    "toast.error": "რაღაც შეცდომა მოხდა",
    "toast.message_sent": "შეტყობინება გაიგზავნა!",
    "toast.checkout_error": "გადახდის ინიციალიზაცია ვერ მოხერხდა. გთხოვთ სცადოთ თავიდან.",
    "toast.product_deleted": "პროდუქტი წაიშალა",
    "toast.product_created": "პროდუქტი შეიქმნა",
    "toast.product_updated": "პროდუქტი განახლდა",
    "toast.order_updated": "შეკვეთა განახლდა",
    "toast.status_updated": "სტატუსი განახლდა",
    "toast.email_sent": "ელ-წერილი გაიგზავნა",
    "toast.tracking_updated": "თვალყურისდევნების ინფო განახლდა",
    "toast.item_added": "დაემატა",
    "toast.item_updated": "განახლდა",
    "toast.item_deleted": "წაიშალა",
    "toast.failed_delete": "წაშლა ვერ მოხერხდა",
    "toast.image_uploaded": "სურათი აიტვირთა",
    "toast.upload_failed": "ატვირთვა ვერ მოხერხდა",
    "toast.order_deleted": "შეკვეთა წაიშალა ისტორიიდან",

    // Admin Navigation
    "admin.nav.dashboard": "მთავარი პანელი",
    "admin.nav.products": "პროდუქტები",
    "admin.nav.catalysts": "კატალიზატორები",
    "admin.nav.orders": "შეკვეთები",
    "admin.nav.catalog": "კატალოგის პარამეტრები",
    "admin.nav.logout": "გასვლა",
    "admin.back_to_store": "← მაღაზიაში დაბრუნება",
    "admin.title": "ადმინი",

    // Catalysts Page
    "catalysts.title": "კატალიზატორები",
    "catalysts.subtitle": "ავტომობილის კატალიზატორების კატალოგი",
    "catalysts.categories": "კატეგორიები",
    "catalysts.search_placeholder": "კატალიზატორის ძებნა...",
    "catalysts.no_results": "შედეგი ვერ მოიძებნა",
    "catalysts.empty_categories": "კატეგორიები არ არის დამატებული",
    "catalysts.empty_products": "ამ კატეგორიაში კატალიზატორები არ არის",

    // Admin Catalysts
    "admin.catalysts.title": "კატალიზატორები",
    "admin.catalysts.categories_tab": "კატეგორიები",
    "admin.catalysts.items_tab": "კატალიზატორები",
    "admin.catalysts.add_category": "კატეგორიის დამატება",
    "admin.catalysts.add_item": "კატალიზატორის დამატება",
    "admin.catalysts.name": "სახელი",
    "admin.catalysts.description": "აღწერა",
    "admin.catalysts.photo": "ფოტო",
    "admin.catalysts.code": "კოდი",
    "admin.catalysts.category": "კატეგორია",
    "admin.catalysts.actions": "მოქმედებები",
    "admin.catalysts.edit": "რედაქტირება",
    "admin.catalysts.delete": "წაშლა",
    "admin.catalysts.delete_blocked": "ჯერ წაშალეთ ამ კატეგორიის კატალიზატორები",

    // Admin Login
    "admin.login.title": "ადმინის შესვლა",
    "admin.login.subtitle": "შედით მაღაზიის სამართავად",
    "admin.login.email": "ელ-ფოსტა",
    "admin.login.password": "პაროლი",
    "admin.login.sign_in": "შესვლა",
    "admin.login.signing_in": "შესვლა...",
    "admin.login.sign_out": "გასვლა",
    "admin.login.access_denied": "წვდომა აკრძალულია",
    "admin.login.access_denied_message": "ამ ანგარიშს არ აქვს ადმინისტრატორის უფლებები.",
    "admin.login.setup_hint": "პირველად? შექმენით ადმინი მომხმარებელი ბექენდის Users პანელიდან, შემდეგ მიანიჭეთ admin როლი user_roles ცხრილში.",
    "admin.login.invalid_email": "არასწორი ელ-ფოსტის მისამართი",
    "admin.login.password_min": "პაროლი უნდა იყოს მინიმუმ 6 სიმბოლო",
    "admin.login.connection_error": "მონაცემთა ბაზის კავშირის შეცდომა",
    "admin.login.backend_error": "ბექენდთან კავშირი ვერ ხერხდება",
    "admin.login.error_invalid_credentials": "არასწორი ელ-ფოსტა ან პაროლი",
    "admin.login.error_email_not_confirmed": "ელ-ფოსტა არ არის დადასტურებული",
    "admin.login.error_user_not_found": "მომხმარებელი ვერ მოიძებნა",
    "admin.login.error_too_many_requests": "ძალიან ბევრი მცდელობა. გთხოვთ მოიცადოთ",

    // Admin Dashboard
    "admin.dashboard.title": "მთავარი პანელი",
    "admin.dashboard.total_products": "სულ პროდუქტები",
    "admin.dashboard.total_orders": "სულ შეკვეთები",
    "admin.dashboard.total_revenue": "სრული შემოსავალი (მიტანილი)",
    "admin.dashboard.pending_orders": "მომლოდინე შეკვეთები",
    "admin.dashboard.quick_actions": "სწრაფი მოქმედებები",
    "admin.dashboard.add_product": "პროდუქტის დამატება",
    "admin.dashboard.add_product_desc": "ახალი პროდუქტის შექმნა",
    "admin.dashboard.view_orders": "შეკვეთების ნახვა",
    "admin.dashboard.view_orders_desc": "მომხმარებელთა შეკვეთების მართვა",
    "admin.dashboard.getting_started": "დასაწყებად",
    "admin.dashboard.step_1": "დაამატეთ პროდუქტები კატალოგში პროდუქტების გვერდიდან",
    "admin.dashboard.step_2": "ჩართეთ სურათები, ფასები და მანქანის თავსებადობა",
    "admin.dashboard.step_3": "თვალყური ადევნეთ შეკვეთებს და განაახლეთ სტატუსები",

    // Admin Products
    "admin.products.title": "პროდუქტები",
    "admin.products.add": "პროდუქტის დამატება",
    "admin.products.search": "პროდუქტების ძებნა...",
    "admin.products.no_products": "პროდუქტი ვერ მოიძებნა",
    "admin.products.add_first": "დაამატეთ პირველი პროდუქტი",
    "admin.products.delete_confirm": "ნამდვილად გსურთ ამ პროდუქტის წაშლა?",
    "admin.products.table.product": "პროდუქტი",
    "admin.products.table.sku": "SKU",
    "admin.products.table.category": "კატეგორია",
    "admin.products.table.price": "ფასი",
    "admin.products.table.stock": "მარაგი",
    "admin.products.table.actions": "მოქმედებები",
    "admin.stock.out_of_stock": "ამოწურულია",
    "admin.stock.low_stock": "დაბალი მარაგი",
    "admin.stock.in_stock": "მარაგშია",

    // Admin Product Form
    "admin.product_form.add_title": "ახალი პროდუქტის დამატება",
    "admin.product_form.edit_title": "პროდუქტის რედაქტირება",
    "admin.product_form.back": "პროდუქტებზე დაბრუნება",
    "admin.product_form.basic_info": "ძირითადი ინფორმაცია",
    "admin.product_form.featured": "მთავარ გვერდზე ჩვენება (გამორჩეული)",
    "admin.product_form.name": "პროდუქტის სახელი",
    "admin.product_form.sku": "SKU",
    "admin.product_form.oem_code": "OEM კოდი",
    "admin.product_form.oem_code_placeholder": "მაგ: 8K0 615 301A",
    "admin.product_form.search_keywords": "საძიებო საკვანძო სიტყვები (მხოლოდ ადმინისთვის)",
    "admin.product_form.search_keywords_placeholder": "დამატებითი სიტყვები ძებნისთვის...",
    "admin.product_form.search_keywords_help": "დაწერეთ დამატებითი სიტყვები და სინონიმები, რომლითაც ეს პროდუქტი მოიძებნება ძებნაში.",
    "admin.product_form.brand": "ბრენდი",
    "admin.product_form.category": "კატეგორია",
    "admin.product_form.select_brand": "აირჩიეთ ბრენდი",
    "admin.product_form.select_category": "აირჩიეთ კატეგორია",
    "admin.product_form.description": "აღწერა",
    "admin.product_form.description_placeholder": "პროდუქტის აღწერა...",
    "admin.product_form.pricing": "ფასი და მარაგი",
    "admin.product_form.price": "ფასი (₾)",
    "admin.product_form.stock": "მარაგის რაოდენობა",
    "admin.product_form.low_stock_threshold": "დაბალი მარაგის ზღვარი",
    "admin.product_form.threshold_hint": "შეტყობინება როცა მარაგი ამ დონეზე ან ქვემოთ იქნება",
    "admin.product_form.image": "პროდუქტის სურათი",
    "admin.product_form.upload": "სურათის ატვირთვა",
    "admin.product_form.uploading": "იტვირთება...",
    "admin.product_form.or_url": "ან შეიყვანეთ URL ქვემოთ",
    "admin.product_form.image_url": "სურათის URL",
    "admin.product_form.no_image": "სურათი არ არის არჩეული",
    "admin.product_form.vehicle": "მანქანის თავსებადობა (არასავალდებულო)",
    "admin.product_form.make": "მარკა",
    "admin.product_form.model": "მოდელი",
    "admin.product_form.all_makes": "ყველა მარკა",
    "admin.product_form.all_models": "ყველა მოდელი",
    "admin.product_form.year_from": "წლიდან",
    "admin.product_form.year_to": "წლამდე",
    "admin.product_form.creating": "შექმნა...",
    "admin.product_form.updating": "განახლება...",
    "admin.product_form.create": "პროდუქტის შექმნა",
    "admin.product_form.update": "პროდუქტის განახლება",
    "admin.product_form.cancel": "გაუქმება",
    "admin.product_form.add_compatibility": "თავსებადობის დამატება",
    "admin.product_form.select_make": "აირჩიეთ მარკა",
    "admin.product_form.select_model": "აირჩიეთ მოდელი",
    "admin.product_form.any_model": "ნებისმიერი მოდელი",
    "admin.product_form.added_compatibilities": "დამატებული თავსებადობები",
    "admin.product_form.remove": "წაშლა",
    "admin.product_form.already_added": "უკვე დამატებულია",
    "admin.product_form.no_models_for_make": "ამ მარკისთვის მოდელები არ მოიძებნა",
    "admin.product_form.compatibility_save_error": "თავსებადობის შენახვა ვერ მოხერხდა",
    "admin.product_form.no_categories": "კატეგორიები ვერ მოიძებნა.",
    "admin.product_form.no_brands": "ბრენდები ვერ მოიძებნა.",
    "admin.product_form.go_to_catalog": "გადადით კატალოგის პარამეტრებში",
    "admin.product_form.to_add_first": "რომ დაამატოთ ჯერ.",

    // Admin Orders
    "admin.orders.title": "შეკვეთები",
    "admin.orders.search": "ძებნა სახელით ან ტელეფონით...",
    "admin.orders.search_by_name_phone": "ძებნა სახელით ან მობილური ნომრით...",
    "admin.orders.no_orders": "შეკვეთები ვერ მოიძებნა",
    "admin.orders.customer_details": "მომხმარებლის დეტალები",
    "admin.orders.shipping_address": "მიწოდების მისამართი",
    "admin.orders.notes": "შენიშვნები",
    "admin.orders.payment_info": "გადახდის ინფორმაცია",
    "admin.orders.order_items": "შეკვეთის ნივთები",
    "admin.orders.loading_items": "ნივთების ჩატვირთვა...",
    "admin.orders.total": "სულ",
    "admin.orders.update_status": "სტატუსის განახლება",
    "admin.orders.shipped_on": "გაიგზავნა",
    "admin.orders.name": "სახელი",
    "admin.orders.phone": "ტელეფონი",
    "admin.orders.method": "მეთოდი",
    "admin.orders.delete_order": "შეკვეთის წაშლა",
    "admin.orders.delete_confirm": "დარწმუნებული ხართ, რომ გნებავთ ამ შეკვეთის წაშლა ადმინ ისტორიდან?",
    "admin.orders.payment_card": "ბარათი (Stripe)",
    "admin.orders.payment_cod": "გადახდა ადგილზე",

    // Admin Catalog
    "admin.catalog.title": "კატალოგის პარამეტრები",
    "admin.catalog.add_new": "ახლის დამატება",
    "admin.catalog.categories": "კატეგორიები",
    "admin.catalog.brands": "ბრენდები",
    "admin.catalog.vehicle_makes": "მანქანის მარკები",
    "admin.catalog.name": "სახელი",
    "admin.catalog.description": "აღწერა",
    "admin.catalog.actions": "მოქმედებები",
    "admin.catalog.no_items": "ელემენტები ვერ მოიძებნა",
    "admin.catalog.add_dialog_title": "დამატება",
    "admin.catalog.edit_dialog_title": "რედაქტირება",
    "admin.catalog.name_required": "სახელი აუცილებელია",
    "admin.catalog.delete_confirm": "ნამდვილად გსურთ ამ ელემენტის წაშლა?",
    "admin.catalog.category_image": "კატეგორიის სურათი",
    "admin.catalog.upload_image": "სურათის ატვირთვა",
    "admin.catalog.remove_image": "სურათის წაშლა",
    "admin.catalog.uploading": "იტვირთება...",

    // Admin Vehicle Models
    "admin.catalog.vehicle_models": "მანქანის მოდელები",
    "admin.vehicle_models.model_name": "მოდელის სახელი",
    "admin.vehicle_models.make": "მარკა",
    "admin.vehicle_models.select_make": "აირჩიეთ მარკა",
    "admin.vehicle_models.make_required": "მარკა აუცილებელია",
    "admin.product_form.add_compatibility_btn": "დამატება",
    "admin.product_form.clear_draft": "დრაფტის წაშლა",
    "admin.product_form.draft_cleared": "დრაფტი გასუფთავდა",

    // Admin Brands
    "admin.brands.top_brand_label": "ტოპ ბრენდი (მთავარ გვერდზე ჩვენება)",
    "admin.brands.top_brand_column": "ტოპ ბრენდი",
    "admin.brands.updated": "ბრენდი წარმატებით განახლდა",

    // Tracking Dialog
    "admin.tracking.ship_order": "შეკვეთის გაგზავნა",
    "admin.tracking.edit_tracking": "თვალყურისდევნების რედაქტირება",
    "admin.tracking.ship_description": "შეიყვანეთ თვალყურისდევნების ინფორმაცია შეკვეთის გაგზავნილად მონიშვნამდე.",
    "admin.tracking.edit_description": "განაახლეთ ამ შეკვეთის თვალყურისდევნების ინფორმაცია.",
    "admin.tracking.tracking_number": "თვალყურისდევნების ნომერი",
    "admin.tracking.carrier": "გადამზიდავი",
    "admin.tracking.select_carrier": "აირჩიეთ გადამზიდავი",
    "admin.tracking.tracking_url": "თვალყურისდევნების URL (არასავალდებულო)",
    "admin.tracking.url_hint": "სრული URL სადაც მომხმარებელს შეუძლია გზავნილის თვალყურისდევნება",
    "admin.tracking.cancel": "გაუქმება",
    "admin.tracking.save": "ცვლილებების შენახვა",
    "admin.tracking.ship": "შეკვეთის გაგზავნა",
    "admin.tracking.saving": "შენახვა...",
  },
  en: {
    // Site name
    "site.name": "Auto Center",
    
    // Navigation
    "nav.home": "Home",
    "nav.shop": "Shop",
    "nav.catalysts": "Catalysts",
    "nav.track_order": "Track Order",
    "nav.brands": "Brands",
    "nav.contact": "Contact",
    
    // Header
    "header.search_placeholder": "Search parts...",
    
    // Hero
    "hero.badge": "Free Shipping on Orders Over ₾99",
    "hero.title_1": "Everything for Your Car",
    "hero.title_2": "In One Place",
    "hero.browse_parts": "Browse Parts",
    "hero.quality_guaranteed": "Quality Guaranteed",
    "hero.fast_delivery": "Fast Delivery",
    
    // Categories
    "categories.title": "Shop by Category",
    "categories.subtitle": "Browse our extensive catalog of automotive parts organized by category",
    
    // Category names
    "category.Brakes": "Brakes",
    "category.Suspension": "Suspension",
    "category.Engine": "Engine",
    "category.Lighting": "Lighting",
    "category.Exhaust": "Exhaust",
    "category.Transmission": "Transmission",
    "category.Electrical": "Electrical",
    "category.Body Parts": "Body Parts",
    "category.Interior": "Interior",
    "category.Wheels & Tires": "Wheels & Tires",
    
    // Featured Products
    "featured.title": "Featured Products",
    "featured.subtitle": "Top picks from our auto parts collection",
    "featured.add_to_cart": "Add to Cart",
    "featured.view_details": "View Details",
    "featured.view_all": "View all",
    
    // Brands
    "brands.title": "Top Brands",
    "brands.subtitle": "We stock parts from the world's leading automotive manufacturers",
    
    // Shop
    "shop.title": "Shop Parts",
    "shop.products_found": "products found",
    "shop.search_products": "Search products...",
    "shop.filters": "Filters",
    "shop.no_products": "No products found",
    "shop.clear_filters": "Clear Filters",
    "shop.clear_all_filters": "Clear All Filters",
    
    // Filters
    "filter.find_by_vehicle": "Find by Vehicle",
    "filter.all_years": "All Years",
    "filter.all_makes": "All Makes",
    "filter.all_models": "All Models",
    "filter.category": "Category",
    "filter.all_categories": "All Categories",
    "filter.brand": "Brand",
    "filter.all_brands": "All Brands",
    "filter.price_range": "Price Range",
    "filter.min": "Min",
    "filter.max": "Max",
    
    // Product
    "product.add_to_cart": "Add to Cart",
    "product.in_stock": "In Stock",
    "product.out_of_stock": "Out of Stock",
    "product.sku": "SKU",
    "product.oem_code": "OEM Code",
    "product.brand": "Brand",
    "product.category": "Category",
    "product.compatibility": "Compatibility",
    "product.description": "Description",
    "product.related": "Related Products",
    "product.fits": "Fits",
    "product.present": "present",
    
    // Cart
    "cart.title": "Shopping Cart",
    "cart.empty": "Your Cart is Empty",
    "cart.empty_desc": "Looks like you haven't added any parts yet.",
    "cart.start_shopping": "Start Shopping",
    "cart.subtotal": "Subtotal",
    "cart.shipping": "Shipping",
    "cart.free": "FREE",
    "cart.free_shipping_note": "Free shipping on orders over ₾99",
    "cart.total": "Total",
    "cart.proceed_checkout": "Proceed to Checkout",
    "cart.continue_shopping": "Continue Shopping",
    "cart.order_summary": "Order Summary",
    
    // Checkout
    "checkout.title": "Checkout",
    "checkout.back_to_cart": "Back to Cart",
    "checkout.contact_info": "Contact Information",
    "checkout.full_name": "Full Name",
    "checkout.email": "Email",
    "checkout.phone": "Phone",
    "checkout.shipping_address": "Shipping Address",
    "checkout.street_address": "Street Address",
    "checkout.city": "City",
    "checkout.postal_code": "Postal Code",
    "checkout.country": "Country",
    "checkout.additional_comment": "Additional Comment",
    "checkout.notes_placeholder": "Any special instructions for your order...",
    "checkout.payment": "Payment Method",
    "checkout.cod_title": "Cash on Delivery",
    "checkout.cod_description": "Pay with cash or bank transfer upon delivery.",
    "checkout.place_order": "Place Order",
    "checkout.name_required": "Name is required",
    "checkout.phone_required": "Phone is required",
    "checkout.country_required": "Country is required",
    "checkout.city_required": "City is required",
    "checkout.street_required": "Street address is required",
    "checkout.postal_required": "Postal code is required",
    "checkout.processing": "Processing...",
    "checkout.phone_notice": "Our customer service will contact you by phone about shipping details.",
    
    // Checkout Success
    "success.title": "Order Placed Successfully!",
    "success.thank_you": "Thank you for your purchase. Your order has been confirmed and is being processed.",
    "success.order_id": "Order ID",
    "success.cod_notice": "Pay with cash or bank transfer to the courier upon delivery.",
    "success.phone_notice": "We will contact you by phone about shipping details.",
    "success.continue_shopping": "Continue Shopping",
    "success.track_order": "Track Your Order",
    "success.order_status_note": "You can check your order status anytime on our",
    
    // Checkout Cancel
    "cancel.title": "Payment Canceled",
    "cancel.message": "Your payment was canceled. Don't worry - your cart items are still saved and you can try again when you're ready.",
    "cancel.retry": "Retry Payment",
    "cancel.return_to_cart": "Return to Cart",
    
    // Contact
    "contact.title": "Contact Us",
    "contact.subtitle": "Have questions about our parts or need help with your order? We're here to help.",
    "contact.phone": "Phone",
    "contact.email": "Email",
    "contact.reply_time": "We reply within 24 hours",
    "contact.address": "Address",
    "contact.name": "Name",
    "contact.subject": "Subject",
    "contact.message": "Message",
    "contact.send": "Send Message",
    "contact.sending": "Sending...",
    "contact.sent": "Message sent!",
    "contact.sent_desc": "We'll get back to you soon.",
    "contact.error": "Failed to send message. Please try again.",
    "contact.phone_optional": "Phone (optional)",
    
    // Order Lookup
    "order_lookup.title": "Order Lookup",
    "order_lookup.subtitle": "Enter your order ID and phone number to check your order status and tracking information.",
    "order_lookup.find_order": "Find Your Order",
    "order_lookup.order_id": "Order ID",
    "order_lookup.phone": "Phone Number",
    "order_lookup.hint": "Use the order ID (e.g., #ABC12345) and your phone number",
    "order_lookup.search": "Find My Order",
    "order_lookup.searching": "Searching...",
    "order_lookup.not_found": "We couldn't find an order with that combination of order ID and phone number.",
    "order_lookup.tracking": "Tracking Information",
    "order_lookup.tracking_number": "Tracking Number",
    "order_lookup.carrier": "Carrier",
    "order_lookup.shipped_on": "Shipped On",
    "order_lookup.track_shipment": "Track Your Shipment",
    "order_lookup.no_tracking": "Tracking details are not available yet. You'll receive an email when your order ships.",
    "order_lookup.order_items": "Order Items",
    "order_lookup.payment": "Payment",
    "order_lookup.method": "Method",
    "order_lookup.status": "Status",
    "order_lookup.shipping_address": "Shipping Address",
    
    // Order statuses
    "status.pending": "pending",
    "status.confirmed": "confirmed",
    "status.shipped": "shipped",
    "status.completed": "completed",
    "status.canceled": "canceled",
    "status.paid": "paid",
    "status.failed": "failed",
    
    "status_message.pending": "Your order is awaiting confirmation.",
    "status_message.confirmed": "Your order has been confirmed and is being prepared.",
    "status_message.shipped": "Your order is on its way!",
    "status_message.completed": "Your order has been delivered.",
    "status_message.canceled": "This order has been canceled.",
    
    // Footer
    "footer.description": "Your trusted source for quality auto parts. We offer a wide selection for all major automobile brands.",
    "footer.contact": "Contact",
    "footer.rights_reserved": "All rights reserved.",
    "footer.admin": "Admin",
    "footer.track_order": "Track Your Order",
    "footer.social": "Social Media",
    "footer.available_24_7": "Available 24/7",
    "footer.hours_weekday": "Mon-Sat 9:00-19:00",
    "footer.hours_sunday": "Sunday 9:00-17:00",
    
    // 404
    "notfound.title": "404",
    "notfound.message": "Oops! Page not found",
    "notfound.return": "Return to Home",
    
    // Common
    "common.loading": "Loading...",
    "common.error": "Error",
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.delete": "Delete",
    "common.edit": "Edit",
    "common.add": "Add",
    "common.qty": "Qty",
    "common.yes": "Yes",
    "common.no": "No",
    "common.confirm": "Confirm",
    "common.actions": "Actions",
    "common.name": "Name",
    "common.description": "Description",
    "common.create": "Create",
    "common.update": "Update",
    
    // Toasts
    "toast.added_to_cart": "Added to cart",
    "toast.removed_from_cart": "Removed from cart",
    "toast.cart_updated": "Cart updated",
    "toast.error": "Something went wrong",
    "toast.message_sent": "Message sent!",
    "toast.checkout_error": "Failed to initialize payment. Please try again.",
    "toast.product_deleted": "Product deleted",
    "toast.product_created": "Product created",
    "toast.product_updated": "Product updated",
    "toast.order_updated": "Order updated",
    "toast.status_updated": "Status updated",
    "toast.email_sent": "Email sent",
    "toast.tracking_updated": "Tracking info updated",
    "toast.item_added": "Added",
    "toast.item_updated": "Updated",
    "toast.item_deleted": "Deleted",
    "toast.failed_delete": "Failed to delete",
    "toast.image_uploaded": "Image uploaded",
    "toast.upload_failed": "Upload failed",
    "toast.order_deleted": "Order deleted from history",

    // Admin Navigation
    "admin.nav.dashboard": "Dashboard",
    "admin.nav.products": "Products",
    "admin.nav.catalysts": "Catalysts",
    "admin.nav.orders": "Orders",
    "admin.nav.catalog": "Catalog Settings",
    "admin.nav.logout": "Sign Out",
    "admin.back_to_store": "← Back to Store",
    "admin.title": "Admin",

    // Catalysts Page
    "catalysts.title": "Catalysts",
    "catalysts.subtitle": "Catalytic converter catalog",
    "catalysts.categories": "Categories",
    "catalysts.search_placeholder": "Search catalysts...",
    "catalysts.no_results": "No results found",
    "catalysts.empty_categories": "No categories added yet",
    "catalysts.empty_products": "No catalysts in this category",

    // Admin Catalysts
    "admin.catalysts.title": "Catalysts",
    "admin.catalysts.categories_tab": "Categories",
    "admin.catalysts.items_tab": "Catalysts",
    "admin.catalysts.add_category": "Add Category",
    "admin.catalysts.add_item": "Add Catalyst",
    "admin.catalysts.name": "Name",
    "admin.catalysts.description": "Description",
    "admin.catalysts.photo": "Photo",
    "admin.catalysts.code": "Code",
    "admin.catalysts.category": "Category",
    "admin.catalysts.actions": "Actions",
    "admin.catalysts.edit": "Edit",
    "admin.catalysts.delete": "Delete",
    "admin.catalysts.delete_blocked": "Delete catalysts in this category first",

    // Admin Login
    "admin.login.title": "Admin Login",
    "admin.login.subtitle": "Sign in to manage your store",
    "admin.login.email": "Email",
    "admin.login.password": "Password",
    "admin.login.sign_in": "Sign In",
    "admin.login.signing_in": "Signing in...",
    "admin.login.sign_out": "Sign Out",
    "admin.login.access_denied": "Access Denied",
    "admin.login.access_denied_message": "This account does not have admin permissions.",
    "admin.login.setup_hint": "First time setup? Create an admin user via the backend Users panel, then assign the admin role in the user_roles table.",
    "admin.login.invalid_email": "Invalid email address",
    "admin.login.password_min": "Password must be at least 6 characters",
    "admin.login.connection_error": "Database connection error",
    "admin.login.backend_error": "Cannot connect to backend",
    "admin.login.error_invalid_credentials": "Invalid email or password",
    "admin.login.error_email_not_confirmed": "Email not confirmed",
    "admin.login.error_user_not_found": "User not found",
    "admin.login.error_too_many_requests": "Too many login attempts. Please wait",

    // Admin Dashboard
    "admin.dashboard.title": "Dashboard",
    "admin.dashboard.total_products": "Total Products",
    "admin.dashboard.total_orders": "Total Orders",
    "admin.dashboard.total_revenue": "Total Revenue (Completed)",
    "admin.dashboard.pending_orders": "Pending Orders",
    "admin.dashboard.quick_actions": "Quick Actions",
    "admin.dashboard.add_product": "Add New Product",
    "admin.dashboard.add_product_desc": "Create a new product listing",
    "admin.dashboard.view_orders": "View Orders",
    "admin.dashboard.view_orders_desc": "Manage customer orders",
    "admin.dashboard.getting_started": "Getting Started",
    "admin.dashboard.step_1": "Add products to your catalog via the Products page",
    "admin.dashboard.step_2": "Include images, pricing, and vehicle compatibility",
    "admin.dashboard.step_3": "Monitor orders and update their status as needed",

    // Admin Products
    "admin.products.title": "Products",
    "admin.products.add": "Add Product",
    "admin.products.search": "Search products...",
    "admin.products.no_products": "No products found",
    "admin.products.add_first": "Add your first product",
    "admin.products.delete_confirm": "Are you sure you want to delete this product?",
    "admin.products.table.product": "Product",
    "admin.products.table.sku": "SKU",
    "admin.products.table.category": "Category",
    "admin.products.table.price": "Price",
    "admin.products.table.stock": "Stock",
    "admin.products.table.actions": "Actions",
    "admin.stock.out_of_stock": "Out of stock",
    "admin.stock.low_stock": "Low stock",
    "admin.stock.in_stock": "In stock",

    // Admin Product Form
    "admin.product_form.add_title": "Add New Product",
    "admin.product_form.edit_title": "Edit Product",
    "admin.product_form.back": "Back to Products",
    "admin.product_form.basic_info": "Basic Information",
    "admin.product_form.featured": "Show on homepage (featured)",
    "admin.product_form.name": "Product Name",
    "admin.product_form.sku": "SKU",
    "admin.product_form.oem_code": "OEM Code",
    "admin.product_form.oem_code_placeholder": "e.g. 8K0 615 301A",
    "admin.product_form.search_keywords": "Search Keywords (admin only)",
    "admin.product_form.search_keywords_placeholder": "Additional search terms...",
    "admin.product_form.search_keywords_help": "Add synonyms and keywords to help customers find this product in search.",
    "admin.product_form.brand": "Brand",
    "admin.product_form.category": "Category",
    "admin.product_form.select_brand": "Select Brand",
    "admin.product_form.select_category": "Select Category",
    "admin.product_form.description": "Description",
    "admin.product_form.description_placeholder": "Product description...",
    "admin.product_form.pricing": "Pricing & Inventory",
    "admin.product_form.price": "Price (₾)",
    "admin.product_form.stock": "Stock Quantity",
    "admin.product_form.low_stock_threshold": "Low Stock Threshold",
    "admin.product_form.threshold_hint": "Alert when stock falls at or below this level",
    "admin.product_form.image": "Product Image",
    "admin.product_form.upload": "Upload Image",
    "admin.product_form.uploading": "Uploading...",
    "admin.product_form.or_url": "or enter URL below",
    "admin.product_form.image_url": "Image URL",
    "admin.product_form.no_image": "No image selected",
    "admin.product_form.vehicle": "Vehicle Compatibility (Optional)",
    "admin.product_form.make": "Make",
    "admin.product_form.model": "Model",
    "admin.product_form.all_makes": "All Makes",
    "admin.product_form.all_models": "All Models",
    "admin.product_form.year_from": "Year From",
    "admin.product_form.year_to": "Year To",
    "admin.product_form.creating": "Creating...",
    "admin.product_form.updating": "Updating...",
    "admin.product_form.create": "Create Product",
    "admin.product_form.update": "Update Product",
    "admin.product_form.cancel": "Cancel",
    "admin.product_form.add_compatibility": "Add Compatibility",
    "admin.product_form.select_make": "Select Make",
    "admin.product_form.select_model": "Select Model",
    "admin.product_form.any_model": "Any Model",
    "admin.product_form.added_compatibilities": "Added Compatibilities",
    "admin.product_form.remove": "Remove",
    "admin.product_form.already_added": "Already added",
    "admin.product_form.no_models_for_make": "No models for this make",
    "admin.product_form.compatibility_save_error": "Failed to save compatibility",
    "admin.product_form.no_categories": "No categories found.",
    "admin.product_form.no_brands": "No brands found.",
    "admin.product_form.go_to_catalog": "Go to Catalog Settings",
    "admin.product_form.to_add_first": "to add them first.",

    // Admin Orders
    "admin.orders.title": "Orders",
    "admin.orders.search": "Search by name or phone...",
    "admin.orders.search_by_name_phone": "Search by name or mobile number...",
    "admin.orders.no_orders": "No orders found",
    "admin.orders.customer_details": "Customer Details",
    "admin.orders.shipping_address": "Shipping Address",
    "admin.orders.notes": "Notes",
    "admin.orders.payment_info": "Payment Info",
    "admin.orders.order_items": "Order Items",
    "admin.orders.loading_items": "Loading items...",
    "admin.orders.total": "Total",
    "admin.orders.update_status": "Update Status",
    "admin.orders.shipped_on": "Shipped",
    "admin.orders.name": "Name",
    "admin.orders.phone": "Phone",
    "admin.orders.method": "Method",
    "admin.orders.delete_order": "Delete Order",
    "admin.orders.delete_confirm": "Are you sure you want to delete this order from admin history?",
    "admin.orders.payment_card": "Card (Stripe)",
    "admin.orders.payment_cod": "Cash on Delivery",

    // Admin Catalog
    "admin.catalog.title": "Catalog Settings",
    "admin.catalog.add_new": "Add New",
    "admin.catalog.categories": "Categories",
    "admin.catalog.brands": "Brands",
    "admin.catalog.vehicle_makes": "Vehicle Makes",
    "admin.catalog.name": "Name",
    "admin.catalog.description": "Description",
    "admin.catalog.actions": "Actions",
    "admin.catalog.no_items": "No items found",
    "admin.catalog.add_dialog_title": "Add",
    "admin.catalog.edit_dialog_title": "Edit",
    "admin.catalog.name_required": "Name is required",
    "admin.catalog.delete_confirm": "Are you sure you want to delete this item?",
    "admin.catalog.category_image": "Category Image",
    "admin.catalog.upload_image": "Upload Image",
    "admin.catalog.remove_image": "Remove Image",
    "admin.catalog.uploading": "Uploading...",

    // Admin Vehicle Models
    "admin.catalog.vehicle_models": "Vehicle Models",
    "admin.vehicle_models.model_name": "Model Name",
    "admin.vehicle_models.make": "Make",
    "admin.vehicle_models.select_make": "Select make",
    "admin.vehicle_models.make_required": "Make is required",
    "admin.product_form.add_compatibility_btn": "Add",
    "admin.product_form.clear_draft": "Clear Draft",
    "admin.product_form.draft_cleared": "Draft cleared",

    // Admin Brands
    "admin.brands.top_brand_label": "Top Brand (show on homepage)",
    "admin.brands.top_brand_column": "Top Brand",
    "admin.brands.updated": "Brand updated",

    // Tracking Dialog
    "admin.tracking.ship_order": "Ship Order",
    "admin.tracking.edit_tracking": "Edit Tracking Info",
    "admin.tracking.ship_description": "Enter tracking information before marking the order as shipped.",
    "admin.tracking.edit_description": "Update the tracking information for this order.",
    "admin.tracking.tracking_number": "Tracking Number",
    "admin.tracking.carrier": "Carrier",
    "admin.tracking.select_carrier": "Select carrier",
    "admin.tracking.tracking_url": "Tracking URL (optional)",
    "admin.tracking.url_hint": "Full URL where the customer can track their shipment",
    "admin.tracking.cancel": "Cancel",
    "admin.tracking.save": "Save Changes",
    "admin.tracking.ship": "Ship Order",
    "admin.tracking.saving": "Saving...",
  },
  tr: {
    // Site name
    "site.name": "Auto Center",
    
    // Navigation
    "nav.home": "Ana Sayfa",
    "nav.shop": "Mağaza",
    "nav.catalysts": "Katalizörler",
    "nav.track_order": "Sipariş Takibi",
    "nav.brands": "Markalar",
    "nav.contact": "İletişim",
    
    // Header
    "header.search_placeholder": "Parça ara...",
    
    // Hero
    "hero.badge": "99₾ Üzeri Siparişlerde Ücretsiz Kargo",
    "hero.title_1": "Aracınız İçin Her Şey",
    "hero.title_2": "Tek Bir Yerde",
    "hero.browse_parts": "Parçalara Göz At",
    "hero.quality_guaranteed": "Kalite Garantili",
    "hero.fast_delivery": "Hızlı Teslimat",
    
    // Categories
    "categories.title": "Kategoriye Göre Alışveriş",
    "categories.subtitle": "Kategorilere göre düzenlenmiş geniş otomobil parçaları kataloğumuza göz atın",
    
    // Category names
    "category.Brakes": "Frenler",
    "category.Suspension": "Süspansiyon",
    "category.Engine": "Motor",
    "category.Lighting": "Aydınlatma",
    "category.Exhaust": "Egzoz",
    "category.Transmission": "Şanzıman",
    "category.Electrical": "Elektrik",
    "category.Body Parts": "Gövde Parçaları",
    "category.Interior": "İç Mekan",
    "category.Wheels & Tires": "Jantlar & Lastikler",
    
    // Featured Products
    "featured.title": "Öne Çıkan Ürünler",
    "featured.subtitle": "Otomobil parçaları koleksiyonumuzdan en iyi seçimler",
    "featured.add_to_cart": "Sepete Ekle",
    "featured.view_details": "Detayları Gör",
    "featured.view_all": "Tümünü Gör",
    
    // Brands
    "brands.title": "En İyi Markalar",
    "brands.subtitle": "Dünyanın önde gelen otomotiv üreticilerinin parçalarını stokluoruz",
    
    // Shop
    "shop.title": "Parça Mağazası",
    "shop.products_found": "ürün bulundu",
    "shop.search_products": "Ürün ara...",
    "shop.filters": "Filtreler",
    "shop.no_products": "Ürün bulunamadı",
    "shop.clear_filters": "Filtreleri Temizle",
    "shop.clear_all_filters": "Tüm Filtreleri Temizle",
    
    // Filters
    "filter.find_by_vehicle": "Araça Göre Bul",
    "filter.all_years": "Tüm Yıllar",
    "filter.all_makes": "Tüm Markalar",
    "filter.all_models": "Tüm Modeller",
    "filter.category": "Kategori",
    "filter.all_categories": "Tüm Kategoriler",
    "filter.brand": "Marka",
    "filter.all_brands": "Tüm Markalar",
    "filter.price_range": "Fiyat Aralığı",
    "filter.min": "Min",
    "filter.max": "Maks",
    
    // Product
    "product.add_to_cart": "Sepete Ekle",
    "product.in_stock": "Stokta",
    "product.out_of_stock": "Tükendi",
    "product.sku": "SKU",
    "product.oem_code": "OEM Kodu",
    "product.brand": "Marka",
    "product.category": "Kategori",
    "product.compatibility": "Uyumluluk",
    "product.description": "Açıklama",
    "product.related": "İlgili Ürünler",
    "product.fits": "Uyumlu",
    "product.present": "günümüze",
    
    // Cart
    "cart.title": "Alışveriş Sepeti",
    "cart.empty": "Sepetiniz Boş",
    "cart.empty_desc": "Henüz hiç parça eklememişsiniz.",
    "cart.start_shopping": "Alışverişe Başla",
    "cart.subtotal": "Ara Toplam",
    "cart.shipping": "Kargo",
    "cart.free": "ÜCRETSİZ",
    "cart.free_shipping_note": "99₾ üzeri siparişlerde ücretsiz kargo",
    "cart.total": "Toplam",
    "cart.proceed_checkout": "Ödemeye Geç",
    "cart.continue_shopping": "Alışverişe Devam",
    "cart.order_summary": "Sipariş Özeti",
    
    // Checkout
    "checkout.title": "Ödeme",
    "checkout.back_to_cart": "Sepete Dön",
    "checkout.contact_info": "İletişim Bilgileri",
    "checkout.full_name": "Ad Soyad",
    "checkout.email": "E-posta",
    "checkout.phone": "Telefon",
    "checkout.shipping_address": "Teslimat Adresi",
    "checkout.street_address": "Sokak Adresi",
    "checkout.city": "Şehir",
    "checkout.postal_code": "Posta Kodu",
    "checkout.country": "Ülke",
    "checkout.additional_comment": "Ek Yorum",
    "checkout.notes_placeholder": "Siparişiniz için özel talimatlar...",
    "checkout.payment": "Ödeme Yöntemi",
    "checkout.cod_title": "Kapıda Ödeme",
    "checkout.cod_description": "Teslimat sırasında nakit veya banka havalesi ile ödeme yapın.",
    "checkout.place_order": "Sipariş Ver",
    "checkout.name_required": "Ad gerekli",
    "checkout.phone_required": "Telefon gerekli",
    "checkout.country_required": "Ülke gerekli",
    "checkout.city_required": "Şehir gerekli",
    "checkout.street_required": "Sokak adresi gerekli",
    "checkout.postal_required": "Posta kodu gerekli",
    "checkout.processing": "İşleniyor...",
    "checkout.phone_notice": "Müşteri hizmetlerimiz teslimat detayları hakkında sizi telefonla arayacaktır.",
    
    // Checkout Success
    "success.title": "Sipariş Başarıyla Verildi!",
    "success.thank_you": "Satın aldığınız için teşekkürler. Siparişiniz onaylandı ve işleme alındı.",
    "success.order_id": "Sipariş ID",
    "success.cod_notice": "Teslimat sırasında kurye ile nakit veya banka havalesi ile ödeme yapın.",
    "success.phone_notice": "Teslimat detayları hakkında sizi telefonla arayacağız.",
    "success.continue_shopping": "Alışverişe Devam",
    "success.track_order": "Siparişinizi Takip Edin",
    "success.order_status_note": "Sipariş durumunuzu istediğiniz zaman kontrol edebilirsiniz",
    
    // Checkout Cancel
    "cancel.title": "Ödeme İptal Edildi",
    "cancel.message": "Ödemeniz iptal edildi. Endişelenmeyin - sepetinizdeki ürünler hala kayıtlı ve hazır olduğunuzda tekrar deneyebilirsiniz.",
    "cancel.retry": "Tekrar Dene",
    "cancel.return_to_cart": "Sepete Dön",
    
    // Contact
    "contact.title": "Bize Ulaşın",
    "contact.subtitle": "Parçalarımız hakkında sorularınız mı var veya siparişinizle ilgili yardıma mı ihtiyacınız var? Yardıma hazırız.",
    "contact.phone": "Telefon",
    "contact.email": "E-posta",
    "contact.reply_time": "24 saat içinde yanıt veriyoruz",
    "contact.address": "Adres",
    "contact.name": "Ad",
    "contact.subject": "Konu",
    "contact.message": "Mesaj",
    "contact.send": "Mesaj Gönder",
    "contact.sending": "Gönderiliyor...",
    "contact.sent": "Mesaj gönderildi!",
    "contact.sent_desc": "En kısa sürede size döneceğiz.",
    "contact.error": "Mesaj gönderilemedi. Lütfen tekrar deneyin.",
    "contact.phone_optional": "Telefon (opsiyonel)",
    
    // Order Lookup
    "order_lookup.title": "Sipariş Sorgula",
    "order_lookup.subtitle": "Sipariş durumunuzu ve takip bilgilerinizi kontrol etmek için sipariş ID ve telefon numaranızı girin.",
    "order_lookup.find_order": "Siparişinizi Bulun",
    "order_lookup.order_id": "Sipariş ID",
    "order_lookup.phone": "Telefon Numarası",
    "order_lookup.hint": "Sipariş ID (örn., #ABC12345) ve telefon numaranızı kullanın",
    "order_lookup.search": "Siparişimi Bul",
    "order_lookup.searching": "Aranıyor...",
    "order_lookup.not_found": "Bu sipariş ID ve telefon numarası kombinasyonu ile bir sipariş bulamadık.",
    "order_lookup.tracking": "Takip Bilgileri",
    "order_lookup.tracking_number": "Takip Numarası",
    "order_lookup.carrier": "Taşıyıcı",
    "order_lookup.shipped_on": "Gönderim Tarihi",
    "order_lookup.track_shipment": "Gönderinizi Takip Edin",
    "order_lookup.no_tracking": "Takip detayları henüz mevcut değil. Siparişiniz gönderildiğinde bir e-posta alacaksınız.",
    "order_lookup.order_items": "Sipariş Öğeleri",
    "order_lookup.payment": "Ödeme",
    "order_lookup.method": "Yöntem",
    "order_lookup.status": "Durum",
    "order_lookup.shipping_address": "Teslimat Adresi",
    
    // Order statuses
    "status.pending": "beklemede",
    "status.confirmed": "onaylandı",
    "status.shipped": "gönderildi",
    "status.completed": "tamamlandı",
    "status.canceled": "iptal edildi",
    "status.paid": "ödendi",
    "status.failed": "başarısız",
    
    "status_message.pending": "Siparişiniz onay bekliyor.",
    "status_message.confirmed": "Siparişiniz onaylandı ve hazırlanıyor.",
    "status_message.shipped": "Siparişiniz yolda!",
    "status_message.completed": "Siparişiniz teslim edildi.",
    "status_message.canceled": "Bu sipariş iptal edildi.",
    
    // Footer
    "footer.description": "Kaliteli oto parçaları için güvenilir kaynağınız. Tüm büyük otomobil markaları için geniş seçenek sunuyoruz.",
    "footer.contact": "İletişim",
    "footer.rights_reserved": "Tüm hakları saklıdır.",
    "footer.admin": "Yönetici",
    "footer.track_order": "Siparişinizi Takip Edin",
    "footer.social": "Sosyal Medya",
    "footer.available_24_7": "7/24 Ulaşılabilir",
    "footer.hours_weekday": "Pzt-Cts 9:00-19:00",
    "footer.hours_sunday": "Pazar 9:00-17:00",
    
    // 404
    "notfound.title": "404",
    "notfound.message": "Oops! Sayfa bulunamadı",
    "notfound.return": "Ana Sayfaya Dön",
    
    // Common
    "common.loading": "Yükleniyor...",
    "common.error": "Hata",
    "common.save": "Kaydet",
    "common.cancel": "İptal",
    "common.delete": "Sil",
    "common.edit": "Düzenle",
    "common.add": "Ekle",
    "common.qty": "Adet",
    "common.yes": "Evet",
    "common.no": "Hayır",
    "common.confirm": "Onayla",
    "common.actions": "İşlemler",
    "common.name": "Ad",
    "common.description": "Açıklama",
    "common.create": "Oluştur",
    "common.update": "Güncelle",
    
    // Toasts
    "toast.added_to_cart": "Sepete eklendi",
    "toast.removed_from_cart": "Sepetten çıkarıldı",
    "toast.cart_updated": "Sepet güncellendi",
    "toast.error": "Bir şeyler yanlış gitti",
    "toast.message_sent": "Mesaj gönderildi!",
    "toast.checkout_error": "Ödeme başlatılamadı. Lütfen tekrar deneyin.",
    "toast.product_deleted": "Ürün silindi",
    "toast.product_created": "Ürün oluşturuldu",
    "toast.product_updated": "Ürün güncellendi",
    "toast.order_updated": "Sipariş güncellendi",
    "toast.status_updated": "Durum güncellendi",
    "toast.email_sent": "E-posta gönderildi",
    "toast.tracking_updated": "Takip bilgisi güncellendi",
    "toast.item_added": "Eklendi",
    "toast.item_updated": "Güncellendi",
    "toast.item_deleted": "Silindi",
    "toast.failed_delete": "Silinemedi",
    "toast.image_uploaded": "Görsel yüklendi",
    "toast.upload_failed": "Yükleme başarısız",
    "toast.order_deleted": "Sipariş geçmişten silindi",

    // Admin Navigation
    "admin.nav.dashboard": "Kontrol Paneli",
    "admin.nav.products": "Ürünler",
    "admin.nav.catalysts": "Katalizörler",
    "admin.nav.orders": "Siparişler",
    "admin.nav.catalog": "Katalog Ayarları",
    "admin.nav.logout": "Çıkış Yap",
    "admin.back_to_store": "← Mağazaya Dön",
    "admin.title": "Yönetici",

    // Catalysts Page
    "catalysts.title": "Katalizörler",
    "catalysts.subtitle": "Katalitik konvertör kataloğu",
    "catalysts.categories": "Kategoriler",
    "catalysts.search_placeholder": "Katalizör ara...",
    "catalysts.no_results": "Sonuç bulunamadı",
    "catalysts.empty_categories": "Henüz kategori eklenmedi",
    "catalysts.empty_products": "Bu kategoride katalizör yok",

    // Admin Catalysts
    "admin.catalysts.title": "Katalizörler",
    "admin.catalysts.categories_tab": "Kategoriler",
    "admin.catalysts.items_tab": "Katalizörler",
    "admin.catalysts.add_category": "Kategori Ekle",
    "admin.catalysts.add_item": "Katalizör Ekle",
    "admin.catalysts.name": "Ad",
    "admin.catalysts.description": "Açıklama",
    "admin.catalysts.photo": "Fotoğraf",
    "admin.catalysts.code": "Kod",
    "admin.catalysts.category": "Kategori",
    "admin.catalysts.actions": "İşlemler",
    "admin.catalysts.edit": "Düzenle",
    "admin.catalysts.delete": "Sil",
    "admin.catalysts.delete_blocked": "Önce bu kategorideki katalizörleri silin",

    // Admin Login
    "admin.login.title": "Yönetici Girişi",
    "admin.login.subtitle": "Mağazanızı yönetmek için giriş yapın",
    "admin.login.email": "E-posta",
    "admin.login.password": "Şifre",
    "admin.login.sign_in": "Giriş Yap",
    "admin.login.signing_in": "Giriş yapılıyor...",
    "admin.login.sign_out": "Çıkış Yap",
    "admin.login.access_denied": "Erişim Reddedildi",
    "admin.login.access_denied_message": "Bu hesabın yönetici izinleri yok.",
    "admin.login.setup_hint": "İlk kurulum? Backend Users panelinden bir yönetici kullanıcı oluşturun, ardından user_roles tablosunda admin rolü atayın.",
    "admin.login.invalid_email": "Geçersiz e-posta adresi",
    "admin.login.password_min": "Şifre en az 6 karakter olmalıdır",
    "admin.login.connection_error": "Veritabanı bağlantı hatası",
    "admin.login.backend_error": "Backend'e bağlanılamıyor",
    "admin.login.error_invalid_credentials": "Geçersiz e-posta veya şifre",
    "admin.login.error_email_not_confirmed": "E-posta onaylanmadı",
    "admin.login.error_user_not_found": "Kullanıcı bulunamadı",
    "admin.login.error_too_many_requests": "Çok fazla giriş denemesi. Lütfen bekleyin",

    // Admin Dashboard
    "admin.dashboard.title": "Kontrol Paneli",
    "admin.dashboard.total_products": "Toplam Ürün",
    "admin.dashboard.total_orders": "Toplam Sipariş",
    "admin.dashboard.total_revenue": "Toplam Gelir (Tamamlanan)",
    "admin.dashboard.pending_orders": "Bekleyen Siparişler",
    "admin.dashboard.quick_actions": "Hızlı İşlemler",
    "admin.dashboard.add_product": "Yeni Ürün Ekle",
    "admin.dashboard.add_product_desc": "Yeni bir ürün listesi oluşturun",
    "admin.dashboard.view_orders": "Siparişleri Görüntüle",
    "admin.dashboard.view_orders_desc": "Müşteri siparişlerini yönetin",
    "admin.dashboard.getting_started": "Başlarken",
    "admin.dashboard.step_1": "Ürünler sayfasından kataloğunuza ürün ekleyin",
    "admin.dashboard.step_2": "Görseller, fiyatlandırma ve araç uyumluluğu ekleyin",
    "admin.dashboard.step_3": "Siparişleri izleyin ve durumlarını gerektiği gibi güncelleyin",

    // Admin Products
    "admin.products.title": "Ürünler",
    "admin.products.add": "Ürün Ekle",
    "admin.products.search": "Ürün ara...",
    "admin.products.no_products": "Ürün bulunamadı",
    "admin.products.add_first": "İlk ürününüzü ekleyin",
    "admin.products.delete_confirm": "Bu ürünü silmek istediğinizden emin misiniz?",
    "admin.products.table.product": "Ürün",
    "admin.products.table.sku": "SKU",
    "admin.products.table.category": "Kategori",
    "admin.products.table.price": "Fiyat",
    "admin.products.table.stock": "Stok",
    "admin.products.table.actions": "İşlemler",
    "admin.stock.out_of_stock": "Tükendi",
    "admin.stock.low_stock": "Düşük stok",
    "admin.stock.in_stock": "Stokta",

    // Admin Product Form
    "admin.product_form.add_title": "Yeni Ürün Ekle",
    "admin.product_form.edit_title": "Ürünü Düzenle",
    "admin.product_form.back": "Ürünlere Dön",
    "admin.product_form.basic_info": "Temel Bilgiler",
    "admin.product_form.featured": "Ana sayfada göster (öne çıkan)",
    "admin.product_form.name": "Ürün Adı",
    "admin.product_form.sku": "SKU",
    "admin.product_form.oem_code": "OEM Kodu",
    "admin.product_form.oem_code_placeholder": "örn. 8K0 615 301A",
    "admin.product_form.search_keywords": "Arama Anahtar Kelimeleri (sadece yönetici)",
    "admin.product_form.search_keywords_placeholder": "Ek arama terimleri...",
    "admin.product_form.search_keywords_help": "Müşterilerin bu ürünü aramada bulmasına yardımcı olacak eş anlamlılar ve anahtar kelimeler ekleyin.",
    "admin.product_form.brand": "Marka",
    "admin.product_form.category": "Kategori",
    "admin.product_form.select_brand": "Marka Seçin",
    "admin.product_form.select_category": "Kategori Seçin",
    "admin.product_form.description": "Açıklama",
    "admin.product_form.description_placeholder": "Ürün açıklaması...",
    "admin.product_form.pricing": "Fiyatlandırma & Envanter",
    "admin.product_form.price": "Fiyat (₾)",
    "admin.product_form.stock": "Stok Miktarı",
    "admin.product_form.low_stock_threshold": "Düşük Stok Eşiği",
    "admin.product_form.threshold_hint": "Stok bu seviyeye veya altına düştüğünde uyarı",
    "admin.product_form.image": "Ürün Görseli",
    "admin.product_form.upload": "Görsel Yükle",
    "admin.product_form.uploading": "Yükleniyor...",
    "admin.product_form.or_url": "veya aşağıya URL girin",
    "admin.product_form.image_url": "Görsel URL",
    "admin.product_form.no_image": "Görsel seçilmedi",
    "admin.product_form.vehicle": "Araç Uyumluluğu (İsteğe Bağlı)",
    "admin.product_form.make": "Marka",
    "admin.product_form.model": "Model",
    "admin.product_form.all_makes": "Tüm Markalar",
    "admin.product_form.all_models": "Tüm Modeller",
    "admin.product_form.year_from": "Yıldan",
    "admin.product_form.year_to": "Yıla",
    "admin.product_form.creating": "Oluşturuluyor...",
    "admin.product_form.updating": "Güncelleniyor...",
    "admin.product_form.create": "Ürün Oluştur",
    "admin.product_form.update": "Ürünü Güncelle",
    "admin.product_form.cancel": "İptal",
    "admin.product_form.add_compatibility": "Uyumluluk Ekle",
    "admin.product_form.select_make": "Marka Seç",
    "admin.product_form.select_model": "Model Seç",
    "admin.product_form.any_model": "Herhangi Bir Model",
    "admin.product_form.added_compatibilities": "Eklenen Uyumluluklar",
    "admin.product_form.remove": "Kaldır",
    "admin.product_form.already_added": "Zaten eklendi",
    "admin.product_form.no_models_for_make": "Bu marka için model yok",
    "admin.product_form.compatibility_save_error": "Uyumluluk kaydedilemedi",
    "admin.product_form.no_categories": "Kategori bulunamadı.",
    "admin.product_form.no_brands": "Marka bulunamadı.",
    "admin.product_form.go_to_catalog": "Katalog Ayarlarına Git",
    "admin.product_form.to_add_first": "önce eklemek için.",

    // Admin Orders
    "admin.orders.title": "Siparişler",
    "admin.orders.search": "İsim veya telefona göre ara...",
    "admin.orders.search_by_name_phone": "İsim veya cep numarasına göre ara...",
    "admin.orders.no_orders": "Sipariş bulunamadı",
    "admin.orders.customer_details": "Müşteri Detayları",
    "admin.orders.shipping_address": "Teslimat Adresi",
    "admin.orders.notes": "Notlar",
    "admin.orders.payment_info": "Ödeme Bilgisi",
    "admin.orders.order_items": "Sipariş Öğeleri",
    "admin.orders.loading_items": "Öğeler yükleniyor...",
    "admin.orders.total": "Toplam",
    "admin.orders.update_status": "Durumu Güncelle",
    "admin.orders.shipped_on": "Gönderildi",
    "admin.orders.name": "Ad",
    "admin.orders.phone": "Telefon",
    "admin.orders.method": "Yöntem",
    "admin.orders.delete_order": "Siparişi Sil",
    "admin.orders.delete_confirm": "Bu siparişi yönetici geçmişinden silmek istediğinizden emin misiniz?",
    "admin.orders.payment_card": "Kart (Stripe)",
    "admin.orders.payment_cod": "Kapıda Ödeme",

    // Admin Catalog
    "admin.catalog.title": "Katalog Ayarları",
    "admin.catalog.add_new": "Yeni Ekle",
    "admin.catalog.categories": "Kategoriler",
    "admin.catalog.brands": "Markalar",
    "admin.catalog.vehicle_makes": "Araç Markaları",
    "admin.catalog.name": "Ad",
    "admin.catalog.description": "Açıklama",
    "admin.catalog.actions": "İşlemler",
    "admin.catalog.no_items": "Öğe bulunamadı",
    "admin.catalog.add_dialog_title": "Ekle",
    "admin.catalog.edit_dialog_title": "Düzenle",
    "admin.catalog.name_required": "Ad gerekli",
    "admin.catalog.delete_confirm": "Bu öğeyi silmek istediğinizden emin misiniz?",
    "admin.catalog.category_image": "Kategori Resmi",
    "admin.catalog.upload_image": "Resim Yükle",
    "admin.catalog.remove_image": "Resmi Kaldır",
    "admin.catalog.uploading": "Yükleniyor...",

    // Admin Vehicle Models
    "admin.catalog.vehicle_models": "Araç Modelleri",
    "admin.vehicle_models.model_name": "Model Adı",
    "admin.vehicle_models.make": "Marka",
    "admin.vehicle_models.select_make": "Marka seçin",
    "admin.vehicle_models.make_required": "Marka gerekli",
    "admin.product_form.add_compatibility_btn": "Ekle",
    "admin.product_form.clear_draft": "Taslağı Temizle",
    "admin.product_form.draft_cleared": "Taslak temizlendi",

    // Admin Brands
    "admin.brands.top_brand_label": "Üst Marka (ana sayfada göster)",
    "admin.brands.top_brand_column": "Üst Marka",
    "admin.brands.updated": "Marka güncellendi",

    // Tracking Dialog
    "admin.tracking.ship_order": "Siparişi Gönder",
    "admin.tracking.edit_tracking": "Takip Bilgisini Düzenle",
    "admin.tracking.ship_description": "Siparişi gönderildi olarak işaretlemeden önce takip bilgilerini girin.",
    "admin.tracking.edit_description": "Bu siparişin takip bilgilerini güncelleyin.",
    "admin.tracking.tracking_number": "Takip Numarası",
    "admin.tracking.carrier": "Taşıyıcı",
    "admin.tracking.select_carrier": "Taşıyıcı seçin",
    "admin.tracking.tracking_url": "Takip URL (isteğe bağlı)",
    "admin.tracking.url_hint": "Müşterinin gönderisini takip edebileceği tam URL",
    "admin.tracking.cancel": "İptal",
    "admin.tracking.save": "Değişiklikleri Kaydet",
    "admin.tracking.ship": "Siparişi Gönder",
    "admin.tracking.saving": "Kaydediliyor...",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language");
    return (saved === "en" || saved === "ka" || saved === "tr") ? saved : "ka";
  });

  useEffect(() => {
    localStorage.setItem("language", language);
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
  };

  const t = (key: string): string => {
    const result = translations[language][key] || translations.en[key] || key;
    
    // Dev warning for missing translation keys
    if (import.meta.env.DEV && result === key && !key.startsWith("category.") && !key.startsWith("brand.")) {
      console.warn("[i18n missing]", language, key);
    }
    
    return result;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}

/**
 * Helper to translate DB content (category names, brand names, etc.)
 * Returns the translated value if it exists, otherwise returns the fallback (original DB value).
 * This prevents showing raw keys like "category.X" in the UI.
 */
export function translateIfExists(t: (key: string) => string, key: string, fallback: string): string {
  const translated = t(key);
  // If translation returns the key itself, use the fallback
  return translated === key ? fallback : translated;
}
